# Amount of log files to store before removing the oldest one
MAX_LOGFILES: 10
# Log file extension
LOG_FILE_EXTENTSION: ".log"
# Log file timestamp format
LOG_DATE_TIME_FORMAT: "%d%m%Y_%H%M%S"
# Boto3 log level
BOTO3_LOG_LEVEL: "boto3.resources"
# S3 timestamp format
BOTO3_DATE_TIME_FORMAT: "%d%m%Y_%H%M%S" #'%Y.%d.%m-%H.%M.%S.%f'
# Include directory structure from S3 in downloaded files
BOTO3_KEEP_DIRECTORY_STRUCTURE: false

