# Set to 'True' to take no action. Can be used to make sure the AWS connection is working properly before taking any action.
TAKE_NO_ACTION: false
# Amount of log files to store before removing the oldest one
MAX_LOGFILES: 10
# Turn archive management on or/off. This would also turn off the archive clean up.
ARCHIVE_FILES: True
# Turn cleaning up archive on/off.
CLEAN_UP_ARCHIVE: True
# Archive file prefix
ARCHIVE_FILE_PREFIX: ""
# Archive file suffix
ARCHIVE_FILE_SUFFIX: ""
# Archive file time stamp format
ARCHIVE_FILE_TIMESTAMP_FORMAT: "%Y.%d.%m-%H.%M.%S.%f"
# Use archive container
ARCHIVE_CONTAINER: True
# Archive container dir time stamp format
ARCHIVE_CONTAINER_TIMESTAMP_FORMAT: "%Y.%d.%m-%H.%M.%S.%f"
# Archive container dir prefix
ARCHIVE_CONTAINER_PREFIX: ""
# Archive container dir suffix
ARCHIVE_CONTAINER_SUFFIX: ""
# Amount of hours to store transfered files in archive.
ARCHIVE_RETENTION_TIME_HOURS: 1
# Log file extension
LOG_FILE_EXTENTSION: ".log"
# Log file timestamp format
LOG_DATE_TIME_FORMAT: "%d%m%Y_%H%M%S"
# Boto3 log level
BOTO3_LOG_LEVEL: "boto3.resources"
# S3 download container timestamp format
BOTO3_DATE_TIME_FORMAT: "%d%m%Y_%H%M%S" #'%Y.%d.%m-%H.%M.%S.%f'
# Set to 'true' to keep directory structure inside the download container
BOTO3_KEEP_DIRECTORY_STRUCTURE: false
# Set to 'true' to put downloaded S3 objectes in a timestamp named container (directory). Experimental, only works without archiving.  
BOTO3_USE_TIMESTAMP_CONTAINER: false
# Set to 'true' to only download files created after the last archive was created. Only works with archiving.
BOTO3_ONLY_DOWNLOAD_LATEST: true

